// <auto-generated>
// This file contains protocol models for the Clawdbot Gateway.
// Based on: src/gateway/protocol/schema.ts
// Protocol Version: 3
// </auto-generated>

#nullable enable
using System.Text.Json.Serialization;

namespace Clawdbot.Windows.Protocol;

/// <summary>
/// Gateway protocol version
/// </summary>
public static class GatewayProtocol
{
    public const int Version = 3;
    public const int MinVersion = 3;
    public const int MaxVersion = 3;
}

/// <summary>
/// Gateway error codes
/// </summary>
public static class ErrorCodes
{
    public const string NotLinked = "NOT_LINKED";
    public const string NotPaired = "NOT_PAIRED";
    public const string AgentTimeout = "AGENT_TIMEOUT";
    public const string InvalidRequest = "INVALID_REQUEST";
    public const string Unavailable = "UNAVAILABLE";
    public const string ConfigHashMismatch = "CONFIG_HASH_MISMATCH";
}

#region Frame Types

/// <summary>
/// Base class for all Gateway frames
/// </summary>
public abstract record GatewayFrame
{
    [JsonPropertyName("type")]
    public abstract string Type { get; }
}

/// <summary>
/// Request frame sent to Gateway
/// </summary>
public record RequestFrame : GatewayFrame
{
    [JsonPropertyName("type")]
    public override string Type => "request";

    [JsonPropertyName("id")]
    public required string Id { get; init; }

    [JsonPropertyName("method")]
    public required string Method { get; init; }

    [JsonPropertyName("params")]
    public object? Params { get; init; }
}

/// <summary>
/// Response frame received from Gateway
/// </summary>
public record ResponseFrame : GatewayFrame
{
    [JsonPropertyName("type")]
    public override string Type => "response";

    [JsonPropertyName("id")]
    public required string Id { get; init; }

    [JsonPropertyName("payload")]
    public object? Payload { get; init; }

    [JsonPropertyName("error")]
    public GatewayError? Error { get; init; }
}

/// <summary>
/// Event frame pushed by Gateway
/// </summary>
public record EventFrame : GatewayFrame
{
    [JsonPropertyName("type")]
    public override string Type => "event";

    [JsonPropertyName("event")]
    public required string Event { get; init; }

    [JsonPropertyName("payload")]
    public object? Payload { get; init; }
}

/// <summary>
/// Gateway error response
/// </summary>
public record GatewayError
{
    [JsonPropertyName("code")]
    public required string Code { get; init; }

    [JsonPropertyName("message")]
    public required string Message { get; init; }

    [JsonPropertyName("data")]
    public object? Data { get; init; }
}

#endregion

#region Connection Types

/// <summary>
/// Parameters for connecting to Gateway
/// </summary>
public record ConnectParams
{
    [JsonPropertyName("minProtocol")]
    public int MinProtocol { get; init; } = GatewayProtocol.MinVersion;

    [JsonPropertyName("maxProtocol")]
    public int MaxProtocol { get; init; } = GatewayProtocol.MaxVersion;

    [JsonPropertyName("client")]
    public Dictionary<string, object> Client { get; init; } = new()
    {
        ["name"] = "Clawdbot Windows",
        ["version"] = "0.1.0",
        ["platform"] = "windows"
    };

    [JsonPropertyName("caps")]
    public List<string>? Caps { get; init; }

    [JsonPropertyName("commands")]
    public List<string>? Commands { get; init; }

    [JsonPropertyName("role")]
    public string? Role { get; init; }

    [JsonPropertyName("scopes")]
    public List<string>? Scopes { get; init; }
}

/// <summary>
/// Successful hello response from Gateway
/// </summary>
public record HelloOk
{
    [JsonPropertyName("type")]
    public string Type { get; init; } = "hello.ok";

    [JsonPropertyName("protocol")]
    public int Protocol { get; init; }

    [JsonPropertyName("server")]
    public Dictionary<string, object>? Server { get; init; }

    [JsonPropertyName("features")]
    public Dictionary<string, object>? Features { get; init; }

    [JsonPropertyName("snapshot")]
    public Snapshot? Snapshot { get; init; }

    [JsonPropertyName("canvasHostUrl")]
    public string? CanvasHostUrl { get; init; }

    [JsonPropertyName("policy")]
    public Dictionary<string, object>? Policy { get; init; }
}

#endregion

#region Snapshot Types

/// <summary>
/// Full state snapshot from Gateway
/// </summary>
public record Snapshot
{
    [JsonPropertyName("presence")]
    public List<PresenceEntry> Presence { get; init; } = new();

    [JsonPropertyName("health")]
    public object? Health { get; init; }

    [JsonPropertyName("stateVersion")]
    public StateVersion? StateVersion { get; init; }

    [JsonPropertyName("uptimeMs")]
    public long UptimeMs { get; init; }

    [JsonPropertyName("configPath")]
    public string? ConfigPath { get; init; }

    [JsonPropertyName("stateDir")]
    public string? StateDir { get; init; }

    [JsonPropertyName("sessionDefaults")]
    public SessionDefaults? SessionDefaults { get; init; }
}

/// <summary>
/// Presence entry for connected device
/// </summary>
public record PresenceEntry
{
    [JsonPropertyName("host")]
    public string? Host { get; init; }

    [JsonPropertyName("ip")]
    public string? Ip { get; init; }

    [JsonPropertyName("version")]
    public string? Version { get; init; }

    [JsonPropertyName("platform")]
    public string? Platform { get; init; }

    [JsonPropertyName("deviceFamily")]
    public string? DeviceFamily { get; init; }

    [JsonPropertyName("ts")]
    public long Ts { get; init; }

    [JsonPropertyName("deviceId")]
    public string? DeviceId { get; init; }

    [JsonPropertyName("roles")]
    public List<string>? Roles { get; init; }
}

/// <summary>
/// State version for tracking changes
/// </summary>
public record StateVersion
{
    [JsonPropertyName("presence")]
    public int Presence { get; init; }

    [JsonPropertyName("health")]
    public int Health { get; init; }
}

/// <summary>
/// Session defaults
/// </summary>
public record SessionDefaults
{
    [JsonPropertyName("defaultAgentId")]
    public required string DefaultAgentId { get; init; }

    [JsonPropertyName("mainKey")]
    public required string MainKey { get; init; }

    [JsonPropertyName("mainSessionKey")]
    public required string MainSessionKey { get; init; }

    [JsonPropertyName("scope")]
    public string? Scope { get; init; }
}

#endregion

#region Config Types

/// <summary>
/// Response from config.get
/// </summary>
public record ConfigGetResponse
{
    [JsonPropertyName("raw")]
    public required string Raw { get; init; }

    [JsonPropertyName("hash")]
    public required string Hash { get; init; }

    [JsonPropertyName("path")]
    public required string Path { get; init; }
}

/// <summary>
/// Parameters for config.apply
/// </summary>
public record ConfigApplyParams
{
    [JsonPropertyName("raw")]
    public required string Raw { get; init; }

    [JsonPropertyName("baseHash")]
    public string? BaseHash { get; init; }

    [JsonPropertyName("sessionKey")]
    public string? SessionKey { get; init; }

    [JsonPropertyName("restartDelayMs")]
    public int? RestartDelayMs { get; init; }
}

/// <summary>
/// Parameters for config.patch
/// </summary>
public record ConfigPatchParams
{
    [JsonPropertyName("raw")]
    public required string Raw { get; init; }

    [JsonPropertyName("baseHash")]
    public string? BaseHash { get; init; }

    [JsonPropertyName("sessionKey")]
    public string? SessionKey { get; init; }

    [JsonPropertyName("restartDelayMs")]
    public int? RestartDelayMs { get; init; }
}

/// <summary>
/// Response from config.schema
/// </summary>
public record ConfigSchemaResponse
{
    [JsonPropertyName("schema")]
    public required object Schema { get; init; }

    [JsonPropertyName("uiHints")]
    public Dictionary<string, ConfigUiHint>? UiHints { get; init; }

    [JsonPropertyName("version")]
    public required string Version { get; init; }

    [JsonPropertyName("generatedAt")]
    public required string GeneratedAt { get; init; }
}

/// <summary>
/// UI hints for config schema
/// </summary>
public record ConfigUiHint
{
    [JsonPropertyName("label")]
    public string? Label { get; init; }

    [JsonPropertyName("help")]
    public string? Help { get; init; }

    [JsonPropertyName("group")]
    public string? Group { get; init; }

    [JsonPropertyName("order")]
    public int? Order { get; init; }

    [JsonPropertyName("advanced")]
    public bool? Advanced { get; init; }

    [JsonPropertyName("sensitive")]
    public bool? Sensitive { get; init; }

    [JsonPropertyName("placeholder")]
    public string? Placeholder { get; init; }
}

#endregion

#region Channel Types

/// <summary>
/// Parameters for channels.status
/// </summary>
public record ChannelsStatusParams
{
    [JsonPropertyName("probe")]
    public bool? Probe { get; init; }

    [JsonPropertyName("timeoutMs")]
    public int? TimeoutMs { get; init; }
}

/// <summary>
/// Response from channels.status
/// </summary>
public record ChannelsStatusResponse
{
    [JsonPropertyName("ts")]
    public long Ts { get; init; }

    [JsonPropertyName("channelOrder")]
    public List<string> ChannelOrder { get; init; } = new();

    [JsonPropertyName("channelLabels")]
    public Dictionary<string, string> ChannelLabels { get; init; } = new();

    [JsonPropertyName("channelDetailLabels")]
    public Dictionary<string, string>? ChannelDetailLabels { get; init; }

    [JsonPropertyName("channelAccounts")]
    public Dictionary<string, List<ChannelAccountSnapshot>> ChannelAccounts { get; init; } = new();

    [JsonPropertyName("channelDefaultAccountId")]
    public Dictionary<string, string>? ChannelDefaultAccountId { get; init; }
}

/// <summary>
/// Snapshot for a channel account
/// </summary>
public record ChannelAccountSnapshot
{
    [JsonPropertyName("accountId")]
    public required string AccountId { get; init; }

    [JsonPropertyName("name")]
    public string? Name { get; init; }

    [JsonPropertyName("enabled")]
    public bool? Enabled { get; init; }

    [JsonPropertyName("configured")]
    public bool? Configured { get; init; }

    [JsonPropertyName("linked")]
    public bool? Linked { get; init; }

    [JsonPropertyName("running")]
    public bool? Running { get; init; }

    [JsonPropertyName("connected")]
    public bool? Connected { get; init; }

    [JsonPropertyName("lastConnectedAt")]
    public long? LastConnectedAt { get; init; }

    [JsonPropertyName("lastError")]
    public string? LastError { get; init; }

    [JsonPropertyName("lastInboundAt")]
    public long? LastInboundAt { get; init; }

    [JsonPropertyName("lastOutboundAt")]
    public long? LastOutboundAt { get; init; }
}

/// <summary>
/// Parameters for channels.logout
/// </summary>
public record ChannelsLogoutParams
{
    [JsonPropertyName("channel")]
    public required string Channel { get; init; }

    [JsonPropertyName("accountId")]
    public string? AccountId { get; init; }
}

#endregion

#region Session Types

/// <summary>
/// Parameters for sessions.list
/// </summary>
public record SessionsListParams
{
    [JsonPropertyName("limit")]
    public int? Limit { get; init; }

    [JsonPropertyName("activeMinutes")]
    public int? ActiveMinutes { get; init; }

    [JsonPropertyName("includeGlobal")]
    public bool? IncludeGlobal { get; init; }

    [JsonPropertyName("includeDerivedTitles")]
    public bool? IncludeDerivedTitles { get; init; }

    [JsonPropertyName("includeLastMessage")]
    public bool? IncludeLastMessage { get; init; }

    [JsonPropertyName("agentId")]
    public string? AgentId { get; init; }

    [JsonPropertyName("search")]
    public string? Search { get; init; }
}

/// <summary>
/// Session info
/// </summary>
public record SessionInfo
{
    [JsonPropertyName("key")]
    public required string Key { get; init; }

    [JsonPropertyName("agentId")]
    public string? AgentId { get; init; }

    [JsonPropertyName("label")]
    public string? Label { get; init; }

    [JsonPropertyName("derivedTitle")]
    public string? DerivedTitle { get; init; }

    [JsonPropertyName("lastMessage")]
    public string? LastMessage { get; init; }

    [JsonPropertyName("lastActivityAt")]
    public long? LastActivityAt { get; init; }

    [JsonPropertyName("createdAt")]
    public long? CreatedAt { get; init; }

    [JsonPropertyName("model")]
    public string? Model { get; init; }

    [JsonPropertyName("thinkingLevel")]
    public string? ThinkingLevel { get; init; }
}

/// <summary>
/// Parameters for sessions.patch
/// </summary>
public record SessionsPatchParams
{
    [JsonPropertyName("key")]
    public required string Key { get; init; }

    [JsonPropertyName("label")]
    public string? Label { get; init; }

    [JsonPropertyName("thinkingLevel")]
    public string? ThinkingLevel { get; init; }

    [JsonPropertyName("model")]
    public string? Model { get; init; }

    [JsonPropertyName("sendPolicy")]
    public string? SendPolicy { get; init; }
}

/// <summary>
/// Parameters for sessions.delete
/// </summary>
public record SessionsDeleteParams
{
    [JsonPropertyName("key")]
    public required string Key { get; init; }

    [JsonPropertyName("deleteTranscript")]
    public bool? DeleteTranscript { get; init; }
}

#endregion

#region Exec Approval Types

/// <summary>
/// Response from execApprovals.get
/// </summary>
public record ExecApprovalsGetResponse
{
    [JsonPropertyName("path")]
    public required string Path { get; init; }

    [JsonPropertyName("exists")]
    public bool Exists { get; init; }

    [JsonPropertyName("hash")]
    public required string Hash { get; init; }

    [JsonPropertyName("file")]
    public required ExecApprovalsFile File { get; init; }
}

/// <summary>
/// Exec approvals file structure
/// </summary>
public record ExecApprovalsFile
{
    [JsonPropertyName("version")]
    public int Version { get; init; } = 1;

    [JsonPropertyName("socket")]
    public ExecApprovalsSocket? Socket { get; init; }

    [JsonPropertyName("defaults")]
    public ExecApprovalsDefaults? Defaults { get; init; }

    [JsonPropertyName("agents")]
    public Dictionary<string, ExecApprovalsAgent>? Agents { get; init; }
}

/// <summary>
/// Socket config for exec approvals
/// </summary>
public record ExecApprovalsSocket
{
    [JsonPropertyName("path")]
    public string? Path { get; init; }

    [JsonPropertyName("token")]
    public string? Token { get; init; }
}

/// <summary>
/// Default exec approval settings
/// </summary>
public record ExecApprovalsDefaults
{
    [JsonPropertyName("security")]
    public string? Security { get; init; }

    [JsonPropertyName("ask")]
    public string? Ask { get; init; }

    [JsonPropertyName("askFallback")]
    public string? AskFallback { get; init; }

    [JsonPropertyName("autoAllowSkills")]
    public bool? AutoAllowSkills { get; init; }
}

/// <summary>
/// Per-agent exec approval settings
/// </summary>
public record ExecApprovalsAgent
{
    [JsonPropertyName("security")]
    public string? Security { get; init; }

    [JsonPropertyName("ask")]
    public string? Ask { get; init; }

    [JsonPropertyName("askFallback")]
    public string? AskFallback { get; init; }

    [JsonPropertyName("autoAllowSkills")]
    public bool? AutoAllowSkills { get; init; }

    [JsonPropertyName("allowlist")]
    public List<ExecApprovalsAllowlistEntry>? Allowlist { get; init; }
}

/// <summary>
/// Allowlist entry for exec approvals
/// </summary>
public record ExecApprovalsAllowlistEntry
{
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    [JsonPropertyName("pattern")]
    public required string Pattern { get; init; }

    [JsonPropertyName("lastUsedAt")]
    public long? LastUsedAt { get; init; }

    [JsonPropertyName("lastUsedCommand")]
    public string? LastUsedCommand { get; init; }

    [JsonPropertyName("lastResolvedPath")]
    public string? LastResolvedPath { get; init; }
}

/// <summary>
/// Exec approval request event
/// </summary>
public record ExecApprovalRequest
{
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    [JsonPropertyName("command")]
    public required string Command { get; init; }

    [JsonPropertyName("cwd")]
    public string? Cwd { get; init; }

    [JsonPropertyName("host")]
    public string? Host { get; init; }

    [JsonPropertyName("security")]
    public string? Security { get; init; }

    [JsonPropertyName("ask")]
    public string? Ask { get; init; }

    [JsonPropertyName("agentId")]
    public string? AgentId { get; init; }

    [JsonPropertyName("resolvedPath")]
    public string? ResolvedPath { get; init; }

    [JsonPropertyName("sessionKey")]
    public string? SessionKey { get; init; }

    [JsonPropertyName("timeoutMs")]
    public int? TimeoutMs { get; init; }
}

/// <summary>
/// Parameters for execApproval.resolve
/// </summary>
public record ExecApprovalResolveParams
{
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    [JsonPropertyName("decision")]
    public required string Decision { get; init; }
}

#endregion

#region Cron Types

/// <summary>
/// Cron job
/// </summary>
public record CronJob
{
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    [JsonPropertyName("name")]
    public string? Name { get; init; }

    [JsonPropertyName("schedule")]
    public required string Schedule { get; init; }

    [JsonPropertyName("message")]
    public required string Message { get; init; }

    [JsonPropertyName("sessionKey")]
    public string? SessionKey { get; init; }

    [JsonPropertyName("enabled")]
    public bool Enabled { get; init; } = true;

    [JsonPropertyName("lastRunAt")]
    public long? LastRunAt { get; init; }

    [JsonPropertyName("nextRunAt")]
    public long? NextRunAt { get; init; }
}

/// <summary>
/// Parameters for cron.add
/// </summary>
public record CronAddParams
{
    [JsonPropertyName("name")]
    public string? Name { get; init; }

    [JsonPropertyName("schedule")]
    public required string Schedule { get; init; }

    [JsonPropertyName("message")]
    public required string Message { get; init; }

    [JsonPropertyName("sessionKey")]
    public string? SessionKey { get; init; }

    [JsonPropertyName("enabled")]
    public bool Enabled { get; init; } = true;
}

#endregion
